Iter5
dyupina/shortener pull request #12
Opened 2024-12-11 11:50 UTC by dyupina

Владислав, спасибо большое за ревью! Не разобралась как пересоздать предыдущий PR, поэтому закрыла его и создала этот, новый

2024-12-11 13:29 UTC, zhark0vv commented on cmd/client/main.go
> +// консольный клиент, способный прочитать в stdin очень длинный URL,
Клиентский код лучше удалить, чтобы не повышать сложность проекта. :)
Понимаю, что он из примера, но этот код не несет ценности для основного приложения.

2024-12-11 13:30 UTC, zhark0vv commented on cmd/shortener/main.go
> +	s := *storage.NewURLstorage()
А зачем ты создаешь поинтер, но разыменовываешь его?

2024-12-11 13:31 UTC, zhark0vv commented on cmd/shortener/main.go
> +	controller := &handlers.Controller{}
Пустые поинтеры принято создавать через `new(...)`
В этом конкретном кейсе, лучше сделать функцию-конструктор в пакете `handlers`

2024-12-11 13:32 UTC, zhark0vv commented on internal/handlers/handlers.go
> +		if req.Method != http.MethodGet {
Стоит делегировать это `chi`, как я писал ранее.

2024-12-11 13:32 UTC, zhark0vv commented on internal/handlers/handlers.go
> +		// id := chi.URLParam(req, "id")
Комментарий без смысловой нагрузки.

2024-12-11 13:34 UTC, zhark0vv commented on internal/storage/storage.go
> +	GetData(key string) (string, error)
1. Я не увидел использования этого интерфейса по проекту.
2. Этот интерфейс лучше поместить в место использования, очень рекомендую это [видео](https://www.youtube.com/watch?v=eYHCCht8eX4&ab_channel=%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9%D0%A2%D1%83%D0%B7%D0%BE%D0%B2%E2%80%94Golang).

2024-12-11 13:35 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +			require.Greater(t, len(match), 1, "Ответ должен содержать исходную ссылку") // ответ должен содержать href="https://example_1.com"
Подскажи, пожалуйста, почему здесь используется `Greater`?

2024-12-11 13:38 UTC, zhark0vv commented on internal/handlers/handlers.go
> +func (con *Controller) ShortenURL(c config.Config, s storage.Storage) http.HandlerFunc {
Стоит инкапсулировать `Config` и `Storage` (а лучше создать слой `Service` и использовать его, инкапсулировав в нем `Storage`) внутрь струтуры контроллера, чтобы в сигнатуру метода не просачивались инфраструктурные зависимости.

Также ты зависишь от конкретных реализаций. Стоит абстрагироваться до интерфейса.
Если нужны примеры, приходи в общий чат. :)

2024-12-11 14:31 UTC, dyupina commented on internal/handlers/handlers_test.go
> +			require.Greater(t, len(match), 1, "Ответ должен содержать исходную ссылку") // ответ должен содержать href="https://example_1.com"
Таким образом проверяю, нашлось ли совпадение по регулярному выражению. Если >1, значит нашлось (в match будут href="https://example_1.com" и https://example_1.com)

2024-12-11 14:43 UTC, zhark0vv requested changes

2024-12-11 14:43 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +			require.Greater(t, len(match), 1, "Ответ должен содержать исходную ссылку") // ответ должен содержать href="https://example_1.com"
Понял, лучше не шейрить ресурсы между тестами, тогда не придется дейлать воркараунды, вроде таких.
Лучше, если каждый инстанс теста будет использовать собственный Storage, возможно, даже, собственный Controller, это позволяет изолировать тесты друг от друга и реализовать параллельность, когда она будет необходима.

2024-12-11 14:48 UTC, dyupina commented on internal/handlers/handlers.go
> +		if req.Method != http.MethodGet {
Код в main.go написан аналогично комменту из прошлого PR
`r := chi.NewRouter()
...
r.Post("/", controller.ShortenURL(c, s))
r.Get("/{id}", controller.GetOriginalURL(s))`
В таком случае проверка if req.Method != http.MethodGet не нужна совсем?

2024-12-11 15:31 UTC, dyupina commented on internal/handlers/handlers.go
> +func (con *Controller) ShortenURL(c config.Config, s storage.Storage) http.HandlerFunc {
Я правильно понимаю, что ShortenURL() можно поправить до:
```
func (con *Controller) ShortenURL() http.HandlerFunc {
	return func(res http.ResponseWriter, req *http.Request) {
		body, _ := io.ReadAll(req.Body)
		originalURL := string(body)
		shortID := generateShortID()

		con.storage.UpdateData(shortID, originalURL)

		res.WriteHeader(http.StatusCreated)
		res.Write([]byte(con.config.BaseURL + "/" + shortID))
	}

}
```
где Controller - это 
```
type Controller struct {
	config  *config.Config
	storage *storage.Storage
}
```
Конструктор:
```
func NewController(config *config.Config, storage *storage.Storage) *Controller {
	return &Controller{config: config, storage: storage}
}
```
И интерфейс:
```
type Handler interface {
	ShortenURL() http.HandlerFunc
	GetOriginalURL() http.HandlerFunc
}
```

2024-12-11 15:37 UTC, dyupina commented on internal/storage/storage.go
> +	GetData(key string) (string, error)
GetData() и UpdateData() вызываю в GetOriginalURL() и ShortenURL() соответственно

2024-12-11 15:38 UTC, dyupina commented on cmd/shortener/main.go
> +	s := *storage.NewURLstorage()
Какое-то помутнение :thinking: Поправила, спасибо!

2024-12-12 07:09 UTC, zhark0vv requested changes

2024-12-12 07:09 UTC, zhark0vv commented on internal/storage/storage.go
> +	GetData(key string) (string, error)
Все верно, только используешь ты реализацию Storage, а не интерфейс Repository.

2024-12-12 07:09 UTC, zhark0vv commented on internal/handlers/handlers.go
> +func (con *Controller) ShortenURL(c config.Config, s storage.Storage) http.HandlerFunc {
```go
type storage interface {
	UpdateData(shortID, originalURL string) // обрати внимание, что это приватный интерфейс рядом с пакетом контроллера
}

type Controller struct {
	config  *config.Config //Config можно по реализации, это просто стор
	st storage// А вот тут лучше породить интерфейс
}

func NewController(config *config.Config, st storage) *Controller { // Зависим от интерфейса
	return &Controller{config: config, st: storage}
}


func (con *Controller) ShortenURL() http.HandlerFunc {
	return func(res http.ResponseWriter, req *http.Request) {
		body, _ := io.ReadAll(req.Body)
		originalURL := string(body)
		shortID := generateShortID()

		con.st.UpdateData(shortID, originalURL)

		res.WriteHeader(http.StatusCreated)
		res.Write([]byte(con.config.BaseURL + "/" + shortID))
	}
}
```

2024-12-12 07:09 UTC, zhark0vv commented on internal/handlers/handlers.go
> +		if req.Method != http.MethodGet {
Не нужна, она избыточна, роутер не пустит в хендлер на уровне стандартной мидлвари.

2024-12-12 11:25 UTC, dyupina commented on internal/handlers/handlers.go
> +func (con *Controller) ShortenURL(c config.Config, s storage.Storage) http.HandlerFunc {
Спасибо огромное за помощь! И за терпение к моим ошибкам

2024-12-12 11:26 UTC, dyupina commented on internal/handlers/handlers.go
> +func (con *Controller) ShortenURL(c config.Config, s storage.Storage) http.HandlerFunc {
Новый PR на текущую ветку можно создать только закрыв этот PR (как я в прошлый раз делала)? Или как-то иначе?

2024-12-12 12:35 UTC, zhark0vv commented on internal/handlers/handlers.go
> +func (con *Controller) ShortenURL(c config.Config, s storage.Storage) http.HandlerFunc {
Нужно просто докинуть коммиты и сдать текущий PR.
`https://github.com/dyupina/shortener/pull/12`

P.S. С вопросиками лучше в Пачку, я не всегда мониторю ответы в PR. :)

2024-12-12 14:18 UTC, zhark0vv approved these changes

2024-12-12 14:24 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +			require.Greater(t, len(match), 1, "Ответ должен содержать исходную ссылку") // ответ должен содержать href="https://example_1.com"
Greater можно на Equal менять в таком случае, т.к. при индивидуальном сторе запись останется одна.

2024-12-12 14:24 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +			require.Greater(t, len(match), 1, "Ответ должен содержать исходную ссылку") // ответ должен содержать href="https://example_1.com"
Но это опционально, на самом деле, сейчас с тестом тоже все ок.

2024-12-12 14:25 UTC, dyupina commented on internal/handlers/handlers.go
> +type stor interface {
В самом начале правок у меня VSCode ругался на "store", я подумала что это из-за того, что есть пакет с названием store. Решила так исправить)) Но сейчас снова написала "store" вместо "stor" и все ок. Поправлю обязательно в следующей итерации, мне самой такое имя не нравится))

2024-12-12 14:26 UTC, dyupina commented on internal/handlers/handlers_test.go
> +			require.Greater(t, len(match), 1, "Ответ должен содержать исходную ссылку") // ответ должен содержать href="https://example_1.com"
Поняла, хорошо

2024-12-12 14:36 UTC, merged