Iter9
dyupina/shortener pull request #16
Opened 2024-12-22 18:07 UTC by dyupina

2024-12-23 06:55 UTC, zhark0vv requested changes

2024-12-23 06:55 UTC, zhark0vv commented on internal/storage/storage.go
> +func (s *Storage) GetStorageLen() int {
Ресивер уже называется `Storage`, поэтому метод стоит назвать просто `Len()`

2024-12-23 06:55 UTC, zhark0vv commented on cmd/shortener/main.go
>  	r.Post("/", controller.ShortenURL())
Роутинг лучше вынести из main-пакета в обособленный, например, app/controller.
Лучше, если main создает зависимости, но не определяет их.

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers.go
> +	// берём структуру для хранения сведений об ответе
Лучше убрать эти комментарии по коду.

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers.go
> +	file, _ := os.OpenFile(path, os.O_WRONLY|os.O_APPEND, 0666) //nolint:mnd // read and write permission for all users
Каждый вызов `SaveToURLstorage` пересоздает файловый дескриптор. При большом количестве запросов будет выполнено много накладной работы.

Можно пересмотреть концепцию и держать файл открытым, пока приложение запущено.
Но нужно гарантировать, что приложение действительно закроет файл.
Этого можно добиться с помощью:

1. Отловов паник - recover()
2. Отловов os.Signal на принудительный интеррапт.

--
Также, что можно улучшить:
- сохранение файла - это не задача контроллера, это задача storage;
- лучше, вместо файла, использовать дескрипторы из io (io.Reader/io.Writer) и абстрагировать бекапирование: пусть потребитель решает, что это файл;
- перейти на пуш-модель, используя каналы:
на примере метрик, как можно такое сделать

```
func (st *MemStorage) AddMetric(metric Metric) {
	st.mu.Lock()
	st.metrics = append(st.metrics, metric)
	st.mu.Unlock()
	st.events <- metric // Пушим событие в канал
}

func (st *MemStorage) AutoSave(io.Writer, interval time.Duration) {
	go func() {
		for {
			select {
			case metric := <-st.events: // Обрабатываем новое событие из канала
				writer, err := writerFactory()
				if err != nil {
					log.Printf("error creating writer: %v", err)
					continue
				}

				_, err = writer.Write([]byte(fmt.Sprintf("Metric: %s, Value: %d, Time: %s\n", 
					metric.Name, metric.Value, metric.Time)))
				if err != nil {
					log.Printf("error writing metric: %v", err)
				}

			case <-time.After(interval): // Обработка таймаута
				log.Println("No new metrics received within the interval.")
			}
		}
	}()
}

```

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers.go
> +	logger, err := zap.NewDevelopment()
Логгеру стоит быть выше контроллера, это переиспользуемый компонент.
Его стоит выенести в отдельный пакет и инициализировать в самом верху.

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers.go
> +// Middleware для распаковки gzip-запросов
Комментарии из примеров лучше убрать, это понятно из кода.

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers.go
> +		} else { // strings.Contains(req.Header.Get("Content-Type"), "text/plane") {
Лишний комментарий.

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers.go
> +		var shorturl struct {
Эти промежуточные структуры можно вынести в отдельный go-файл в том же пакете.

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +			require.Equal(t, tc.expectedCode, res.StatusCode, "Код ответа не совпадает с ожидаемым")
Лучше, если комментарии к тестам будут на английском. Это вкусовщина, конечно, но лучше привыкать. :)
Работаю в Мексике, очень сильно не нравится мне API на испанском.))

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +		{method: http.MethodGet, orig: "https://example_1.com", contentType: "text/plane", expectedCode: http.StatusTemporaryRedirect},
текст/самолет 😃 

`text/plain`

2024-12-23 06:55 UTC, zhark0vv commented on internal/handlers/handlers_test.go
> +			fmt.Printf(">>> respGetBody %s\n", respGetBody)
В пакете testing есть свой логгер.

2024-12-23 06:55 UTC, zhark0vv commented on internal/storage/storage.go
> +type StorageJSON struct {
Это часть домена, стоит вынести в отдельный пакет domain/models.

2025-01-05 17:32 UTC, dyupina commented
@zhark0vv , добрый вечер! Про комменты к тредам поняла, буду отвечать.
По комментарию из Практикума "Работу принимаю, оставил парочку косметических комментов" - подскажите, пожалуйста, какие замечания? Не вижу новые треды здесь

2025-01-05 18:21 UTC, zhark0vv approved these changes

2025-01-05 18:21 UTC, zhark0vv commented
> @zhark0vv , добрый вечер! Про комменты к тредам поняла, буду отвечать.
> 
> По комментарию из Практикума "Работу принимаю, оставил парочку косметических комментов" - подскажите, пожалуйста, какие замечания? Не вижу новые треды здесь

Засабмитил, спасибо за пинг!

2025-01-07 17:20 UTC, dyupina commented on internal/storage/storage.go
> +func CloseReader(reader io.Reader) {
Поправила, функция ReadWriteCloserClose()

2025-01-07 17:20 UTC, dyupina commented on cmd/shortener/main.go
> +		return
Добавила

2025-01-07 17:35 UTC, merged